<div style="
    background-color: #fff3cd; 
    border-left: 4px solid #f0ad4e; 
    padding: 10px 12px; 
    border-radius: 6px;
    color: #664d03;
">
测试环境使用cst，Jupyter环境名是cellscape_test
</div>

# 测试`labelme_to_mask`

In [2]:
import cellscape.datasets as dts

dts.labelme_to_mask(
    image_path="library_backgrounds/lib0.png",
    annotation_json_path="library_backgrounds/lib0.json",
    labels=["__ignore__", "_background_", "test"],
    output_dir="library_backgrounds/mask",
)

LabelmeMaskResult(output_dir=PosixPath('library_backgrounds/mask'), sample_id='lib0', class_png_dir=PosixPath('library_backgrounds/mask/SegmentationClass/lib0'), class_png_files={'__ignore__': PosixPath('library_backgrounds/mask/SegmentationClass/lib0/-1___ignore__.png'), '_background_': PosixPath('library_backgrounds/mask/SegmentationClass/lib0/0__background_.png'), 'test': PosixPath('library_backgrounds/mask/SegmentationClass/lib0/1_test.png')}, class_npy=PosixPath('library_backgrounds/mask/SegmentationClassNpy/lib0.npy'), visualization_jpg=PosixPath('library_backgrounds/mask/SegmentationClassVisualization/lib0.jpg'), class_names_file=PosixPath('library_backgrounds/mask/class_names.txt'), labels=('__ignore__', '_background_', 'test'), class_ids={'__ignore__': -1, '_background_': 0, 'test': 1})

## 巨大图片测试

In [3]:
from pathlib import Path
import numpy as np
from PIL import Image

# 参数
out_dir = Path("data/labelme_test")
out_dir.mkdir(exist_ok=True)

width = 20_000
height = 20_000
out_path = out_dir / "random1.tif"

# 生成随机灰度图：uint8, 0-255
img = np.random.randint(
    0, 256,
    size=(height, width),
    dtype=np.uint8
)

# 保存为 TIFF
Image.fromarray(img).save(out_path)

print(f"saved: {out_path}")
print(f"image shape: {img.shape}")
print(f"pixels: {width * height}")

saved: labelme_test/random1.tif
image shape: (20000, 20000)
pixels: 400000000


In [2]:
import cellscape.datasets as dts

dts.labelme_to_mask(
    image_path="data/labelme_test/random1.tif",
    annotation_json_path="data/labelme_test/random1.json",
    labels=["__ignore__", "_background_", "test"],
    output_dir="data/labelme_test/mask",
    allow_large_images=True,
)

LabelmeMaskResult(output_dir=PosixPath('data/labelme_test/mask'), sample_id='random1', class_png_dir=PosixPath('data/labelme_test/mask/SegmentationClass/random1'), class_png_files={'__ignore__': PosixPath('data/labelme_test/mask/SegmentationClass/random1/-1___ignore__.png'), '_background_': PosixPath('data/labelme_test/mask/SegmentationClass/random1/0__background_.png'), 'test': PosixPath('data/labelme_test/mask/SegmentationClass/random1/1_test.png')}, class_npy=PosixPath('data/labelme_test/mask/SegmentationClassNpy/random1.npy'), visualization_jpg=PosixPath('data/labelme_test/mask/SegmentationClassVisualization/random1.jpg'), class_names_file=PosixPath('data/labelme_test/mask/class_names.txt'), labels=('__ignore__', '_background_', 'test'), class_ids={'__ignore__': -1, '_background_': 0, 'test': 1})

In [1]:
import cellscape.datasets as dts

dts.labelme_to_mask(
    image_path="/Volumes/MacPassport/python/bioinformatics_project/MCAO20250929/data/ssDNA/Y00855N1_ssDNA_regist.tif",
    annotation_json_path="/Volumes/MacPassport/python/bioinformatics_project/MCAO20250929/data/ssDNA/Y00855N1_ssDNA_regist.json",
    labels=["V3", "VL"],
    output_dir="data/mask1",
    allow_large_images=True,
)

LabelmeMaskResult(output_dir=PosixPath('data/mask1'), sample_id='Y00855N1_ssDNA_regist', class_png_dir=PosixPath('data/mask1/SegmentationClass/Y00855N1_ssDNA_regist'), class_png_files={'V3': PosixPath('data/mask1/SegmentationClass/Y00855N1_ssDNA_regist/1_V3.png'), 'VL': PosixPath('data/mask1/SegmentationClass/Y00855N1_ssDNA_regist/2_VL.png')}, class_npy=PosixPath('data/mask1/SegmentationClassNpy/Y00855N1_ssDNA_regist.npy'), visualization_jpg=PosixPath('data/mask1/SegmentationClassVisualization/Y00855N1_ssDNA_regist.jpg'), class_names_file=PosixPath('data/mask1/class_names.txt'), labels=('V3', 'VL'), class_ids={'V3': 1, 'VL': 2})

In [2]:
from PIL import Image
Image.MAX_IMAGE_PIXELS = None

image_path = "data/mask1/SegmentationClassVisualization/Y00855N1_ssDNA_regist.jpg"

with Image.open(image_path) as img:
    print("size:", img.size)       # (width, height)
    print("width:", img.width)
    print("height:", img.height)
    print("mode:", img.mode)       # L=灰度, RGB=彩色
    print("format:", img.format)   # TIFF / JPEG / PNG 等

size: (2048, 2048)
width: 2048
height: 2048
mode: RGB
format: JPEG


In [3]:
import numpy as np

arr = np.load("data/mask1/SegmentationClassNpy/Y00855N1_ssDNA_regist.npy")

print(type(arr))
print(arr.shape)
print(arr.dtype)
print(arr)

<class 'numpy.ndarray'>
(2, 23520, 23520)
uint8
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [5]:
!find . -name "._*" -delete -print

./data/mask1/._class_names.txt
./data/mask1/SegmentationClass/Y00855N1_ssDNA_regist/._1_V3.png
./data/mask1/SegmentationClass/Y00855N1_ssDNA_regist/._2_VL.png
./data/mask1/SegmentationClass/._Y00855N1_ssDNA_regist
./data/mask1/._SegmentationClass
./data/mask1/SegmentationClassNpy/._Y00855N1_ssDNA_regist.npy
./data/mask1/._SegmentationClassNpy
./data/mask1/SegmentationClassVisualization/._Y00855N1_ssDNA_regist.jpg
./data/mask1/._SegmentationClassVisualization
./data/._mask1
./__pycache__/._test_labelme.cpython-312.pyc
./__pycache__/._test_labelme.cpython-312-pytest-9.0.3.pyc
./._test_datasets.ipynb
./._test_labelme.py


# 测试`labelme_to_masks`

In [4]:
import cellscape.datasets as dts

dts.labelme_to_masks(
    annotation_dir="library_backgrounds",
    image_dir="library_backgrounds",
    output_dir="library_backgrounds/masks",
    labels=["__ignore__", "_background_", "test"],
)

[LabelmeMaskResult(output_dir=PosixPath('library_backgrounds/masks'), sample_id='lib0', class_png_dir=PosixPath('library_backgrounds/masks/SegmentationClass/lib0'), class_png_files={'__ignore__': PosixPath('library_backgrounds/masks/SegmentationClass/lib0/-1___ignore__.png'), '_background_': PosixPath('library_backgrounds/masks/SegmentationClass/lib0/0__background_.png'), 'test': PosixPath('library_backgrounds/masks/SegmentationClass/lib0/1_test.png')}, class_npy=PosixPath('library_backgrounds/masks/SegmentationClassNpy/lib0.npy'), visualization_jpg=PosixPath('library_backgrounds/masks/SegmentationClassVisualization/lib0.jpg'), class_names_file=PosixPath('library_backgrounds/masks/class_names.txt'), labels=('__ignore__', '_background_', 'test'), class_ids={'__ignore__': -1, '_background_': 0, 'test': 1}),
 LabelmeMaskResult(output_dir=PosixPath('library_backgrounds/masks'), sample_id='lib1', class_png_dir=PosixPath('library_backgrounds/masks/SegmentationClass/lib1'), class_png_files={'